### ISSUE TITLE
Safari private browsing, QUOTA_EXCEEDED_ERR: DOM Exception 22

### ISSUE THREAD

**Issue by elsamoluf** [Wisembly/basil.js#38]
Getting exceptions in our tracker with the message `QUOTA_EXCEEDED_ERR: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.` So far it has come from Safari versions 5.x in private browsing mode. Looking at the Basil code I don't see how this could happen. Maybe it's coming from a browser plugin?

**Comment by guillaumepotier** [comment]
Hum this is strange, thought we catched that one. Basil aim is to prevent these type of errors, I'll try to have a look asap.

Thanks

**Comment by elsamoluf** [comment]
Red herring. This was coming from another package that uses history.

**Comment by guillaumepotier** [comment]
Ok thanks

**Comment by reintroducing** [comment]
Question about this because its something we experienced on our site when using sessionStorage.  If I use `basil.set()` with local storage as the default, is this check implemented during the usage of that method and falls back to something (cookies?) if local storage isnt available or would it produce the error? 

Basically, do I have to run `basil.check('local')` before using `basil.set()` local?

**Comment by guillaumepotier** [comment]
> Basically, do I have to run `basil.check('local')` before using `basil.set()` local?

Yes, this is a "best practice" and should be done at the beginning of your script. Define the storages you want to use, and then add them to Basil if check is successful.

However, [here](https://github.com/Wisembly/basil.js/blob/master/src/basil.js#L30) we'll try to catch exceptions like quota exceeded and that should not be a problem if you do not make the check above. (also, we faced a case where check was successful at the beginning, but storing many things during the script execution made the quota exceeded that why we added this safeguard on the `set` method)

Hope that helps

Best

**Comment by reintroducing** [comment]
Hmm, thats interesting because I'm actually using the native storages like this:

```
// localStorage
Basil.localStorage.get(key);
Basil.localStorage.set(key, value);
```

Do these have those checks built in, then?  If not, what is the recommended way of using these methods with a check for support?  Since I'm not instantiating basil but using it directly as a static I'm not sure of how to go about this.  Do I have to create an instance just to perform this check before each call?

**Comment by guillaumepotier** [comment]
Basil aim is to avoid you using `Basil.localStorage`. But instead instantiate a `basil = Basil()` and use then freely `basil.set()` or `basil.get()`. It should avoid you all the troubles of checking if private browsing mode is on or off, its job is to persist data for you where it fits the best

**Comment by guillaumepotier** [comment]
Ahah no prob. I'm not sure there is a better way to do than an other, this is rather quite personal and rely on what you're trying to do. We do not want to say in the docs "you should do that that way", but instead provide a nice and coherent interface to do a maximum with minimal pain.

Here @Wisembly, while developing [Wisembly](http://wisembly.com) and [Solid](http://getsolid.io), we chose to persist things in every storage possible to be the most sticky possible (we have a lot of users in private browsing mode, on old browsers, on multiple domains and subdomains..). That's why we try to double localStorage by cookies if possible (with no expiration)

In specific cases, you would want to set an expiry, and to do so you'll have to go with the `basil.cookie` interface directly: `basil.cookie.set(key, value, { 'expireDays': days, 'domain': 'mydomain.com' });`

But for all the rest, we do not bother and just use `get` and `set` on basil public api.

Hope this is a bit clearer for how we use and consider basil in our work.

Best

**Comment by reintroducing** [comment]
Thanks, that's what I was thinking and why I ended up using the native storage methods directly through Basil.  I was doing cookie and storage management separately before and now I have it centralized in one module with Basil acting as the way I'm handling the storage mechanism.

I'd love to use the basil API directly the way it was meant to be used but do need the cookie options.  Can I propose allowing that to be passed in the set options. 

Current API:
`basil.set('foo', 'quux', { 'storages': ['cookie', 'local'] });`

Suggested API:
```basil.set('foo', 'quux', { 
    storages: ['cookie', 'local'],
    cookieData: { 'expireDays': days, 'domain': 'mydomain.com', 'secure': true }
});```

This would allow you to still use the normal basil set/get api but also in the same shot, if using cookie storage, also set the cookie data per call.

Thoughts?

**Comment by guillaumepotier** [comment]
Yes indeed, this is a nice suggestion that could work!

If you have time (that I does not have atm) you could submit a PR implementing that (with tests;)) I'd be more than happy to review it and merge it.

Best

**Comment by matghaleb** [comment]
sorry to be late in the conversation but if you want, you can already use:
```
basil.set('foo', 'quux', { storages: ['cookie', 'local'], 'expireDays': days, 'domain': 'mydomain.com', 'secure': true });
```
Your approach might be a little more understandable (as `expireDays`, `domain` and `secure` will be only used by the cookie's storage) so don't hesitate to contribute if you have some time.

**Comment by reintroducing** [comment]
OK, so after going through the tests I get random failures after making my updates which I don't think should be happening.  All I really did is wrap the set call of cookie storage option settings around options.cookieSettings (where it handles the expiration days, domain, and secure) and then updated those to check for options.cookieSettings.whatever as well.  As far as I can tell in the tests this should not be breaking as nothing in the tests is even checking for this it would seem but I continue to get random failures which I'm having a hell of a time troubleshooting :\

**Comment by matghaleb** [comment]
Thx for the warning, test suite should be fixed now.
Tell us if you have any other trouble.

**Comment by reintroducing** [comment]
Thanks, that seems to have fixed the first issue.  The one I'm running into now is that after my addition as described above, I'm getting this failure:
```
05 07 2016 10:44:17.094:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#laWRJDWLg9hpRl_2AAAA with id 53201237
PhantomJS 2.1.1 (Mac OS X 0.0.0) Basil test suite Functional Tests should be able to get all the keys FAILED
	expected [ '42',
	  '1234',
	  'foo',
	  'str',
	  'nb',
	  'obj',
	  'arr',
	  'hello.world',
	  'foo.bar',
	  'hello.42.world.false',
	  'foo.bar.18',
	  'true',
	  'false',
	  'bar',
	  'baz' ] to sort of equal [ 'foo', 'bar', 'baz' ]
	assert@node_modules/karma-sinon-expect/node_modules/expect.js/expect.js:99:38
	eql@node_modules/karma-sinon-expect/node_modules/expect.js/expect.js:214:16
	test/test.js:170:32
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 18 of 18 (1 FAILED) (0.191 secs / 0.181 secs)
npm ERR! Test failed.  See above for more details.
```
If I remove my addition this goes away but again, there is nothing in my addition that I can tell should be affecting this.

Here is what I added in the set call for _storages.cookie:
```
if (options.cookieSettings) {
    // handle expiration days
    if (options.cookieSettings.expireDays) {
        var date = new Date();
        date.setTime(date.getTime() + (options.cookieSettings.expireDays * 24 * 60 * 60 * 1000));
        cookie += '; expires=' + date.toGMTString();
    }
    // handle domain
    if (options.cookieSettings.domain && options.cookieSettings.domain !== document.domain) {
        var _domain = options.cookieSettings.domain.replace(/^\./, '');
        if (document.domain.indexOf(_domain) === -1 || _domain.split('.').length <= 1)
            throw Error('invalid domain');
        cookie += '; domain=' + options.cookieSettings.domain;
    }
    // handle secure
    if (options.cookieSettings.secure === true) {
        cookie += '; secure';
    }
}
```
Wrapped in an options.cookieSettings check and changed the options in there to check for options.cookieSettings.whatever.

Why would this be causing test failures?

**Comment by reintroducing** [comment]
Ah, I think I found the problem, forgot about the global settings :)

**Comment by reintroducing** [comment]
PR submitted. Apologies for spamming this thread so much.
